version: "3"
services:
  web:
     container_name: exampleapp
     restart: always
     build:
     ports:
        - "5000:3000"
  mongo:
     container_name: mymongodatabase
     image: mongo 
     ports: 
         - "27018:27017" 
   